export const states = [
  {_id:1,name:"Andaman and Nicobar Islands"},
  {_id:2,name:"Andhra Pradesh"},
  {_id:3,name:"Arunachal Pradesh"},
  {_id:4,name:"Assam"},
  {_id:5,name:"Bihar"},
  {_id:6,name:"Chandigarh"},
  {_id:7,name:"Chhattisgarh"},
  {_id:8,name:"Dadra and Nagar Haveli"},
  {_id:37,name:"Daman and Diu"},
  {_id:9,name:"Delhi"},
  {_id:10,name:"Goa"},
  {_id:11,name:"Gujarat"},
  {_id:12,name:"Haryana"},
  {_id:13,name:"Himachal Pradesh"},
  {_id:14,name:"Jammu and Kashmir"},
  {_id:15,name:"Jharkhand"},
  {_id:16,name:"Karnataka"},
  {_id:17,name:"Kerala"},
  {_id:18,name:"Ladakh"},
  {_id:19,name:"Lakshadweep"},
  {_id:20,name:"Madhya Pradesh"},
  {_id:21,name:"Maharashtra"},
  {_id:22,name:"Manipur"},
  {_id:23,name:"Meghalaya"},
  {_id:24,name:"Mizoram"},
  {_id:25,name:"Nagaland"},
  {_id:26,name:"Odisha"},
  {_id:27,name:"Puducherry"},
  {_id:28,name:"Punjab"},
  {_id:29,name:"Rajasthan"},
  {_id:30,name:"Sikkim"},
  {_id:31,name:"Tamil Nadu"},
  {_id:32,name:"Telangana"},
  {_id:33,name:"Tripura"},
  {_id:34,name:"Uttar Pradesh"},
  {_id:35,name:"Uttarakhand"},
  {_id:36,name:"West Bengal"}
];